// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");

user_pref("browser.region.network.url", "");
user_pref("browser.region.update.enabled", false);

user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);

user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("browser.urlbar.shortcuts.actions", false);
user_pref("browser.urlbar.shortcuts.bookmarks", false);
user_pref("browser.urlbar.shortcuts.history", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("browser.urlbar.showSearchSuggestionsFirst", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.quickactions", false);
user_pref("browser.urlbar.suggest.recentsearches", false);
user_pref("browser.urlbar.suggest.searches", true);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("browser.urlbar.switchTabs.searchAllContainers", false);
user_pref("browser.urlbar.trimHttps", true);
user_pref("browser.warnOnQuitShortcut", false);
user_pref("captivedetect.canonicalURL", "");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b0bacafe-b0ba-cafe-b0ba-cafeb0bacafe");
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");

user_pref("dom.battery.enabled", false);
user_pref("dom.compression_streams.zstd.enabled", true);
user_pref("dom.css_pseudo_element.enabled", true);
user_pref("dom.events.dataTransfer.mozFile.enabled", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.gamepad.enabled", false);
user_pref("dom.gamepad.extensions.enabled", false);
user_pref("dom.gamepad.haptic_feedback.enabled", false);
user_pref("dom.indexedDB.logging.details", false);
user_pref("dom.indexedDB.logging.enabled", false);
user_pref("dom.indexedDB.preprocessing", true);
user_pref("dom.ipc.processCount.webIsolated", 1);
user_pref("dom.ipc.processHangMonitor", false);
user_pref("dom.ipc.reportProcessHangs", false);
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("dom.vibrator.enabled", true);
user_pref("dom.vr.oculus.enabled", false);
user_pref("dom.vr.oculus.invisible.enabled", false);
user_pref("dom.vr.poseprediction.enabled", false);
user_pref("dom.vr.require-gesture", false);
user_pref("dom.webmidi.enabled", false);
user_pref("dom.webshare.enabled", true);
user_pref("extensions.dataCollectionPermissions.enabled", false);
user_pref("extensions.ml.enabled", false);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.api", "");
user_pref("extensions.pocket.bffApi", "");
user_pref("extensions.pocket.bffRecentSaves", false);
user_pref("extensions.pocket.loggedOutVariant", "");
user_pref("extensions.pocket.oAuthConsumerKey", "");
user_pref("extensions.pocket.oAuthConsumerKeyBff", "");

user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.mlmodel.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webapi.enabled", false);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("findbar.highlightAll", true);
user_pref("geo.enabled", false);

user_pref("identity.fxaccounts.auth.uri", "");
user_pref("identity.fxaccounts.commands.missed.fetch_interval", 0);
user_pref("identity.fxaccounts.commands.remoteTabManagement.enabled", false);
user_pref("identity.fxaccounts.contextParam", "");
user_pref("identity.fxaccounts.oauth.enabled", false);
user_pref("identity.fxaccounts.pairing.enabled", false);
user_pref("identity.fxaccounts.remote.oauth.uri", "");
user_pref("identity.fxaccounts.remote.pairing.uri", "");
user_pref("identity.fxaccounts.remote.profile.uri", "");
user_pref("identity.fxaccounts.remote.root", "");
user_pref("identity.fxaccounts.telemetry.clientAssociationPing.enabled", false);
user_pref("identity.fxaccounts.toolbar.defaultVisible", false);
user_pref("identity.fxaccounts.toolbar.enabled", false);
user_pref("identity.fxaccounts.toolbar.pxiToolbarEnabled.monitorEnabled", false);
user_pref("identity.fxaccounts.toolbar.pxiToolbarEnabled.relayEnabled", false);
user_pref("identity.fxaccounts.toolbar.pxiToolbarEnabled.vpnEnabled", false);

user_pref("image.mem.decode_bytes_at_a_time", 65536);
user_pref("javascript.options.atomics_wait_async", true);
user_pref("javascript.options.wasm_branch_hinting", true);
user_pref("javascript.options.wasm_js_promise_integration", true);
user_pref("javascript.options.wasm_memory_control", true);
user_pref("javascript.options.wasm_moz_intgemm", true);
user_pref("layout.accessiblecaret.enabled_on_touch", false);
user_pref("layout.css.grid-template-masonry-value.enabled", true);
user_pref("layout.css.moz-appearance.enabled", false);
user_pref("layout.frame_rate", 165);

user_pref("media.allow-audio-non-utility", true);
user_pref("media.autoplay.default", 0);
user_pref("media.cache_readahead_limit", 7200);
user_pref("media.cache_resume_threshold", 3600);

user_pref("media.hardwaremediakeys.enabled", false);
user_pref("media.navigator.mozgetusermedia.enabled", false);
user_pref("media.peerconnection.description.legacy.enabled", false);
user_pref("media.webrtc.camera.allow-pipewire", true);
user_pref("media.webrtc.codec.video.av1.experimental_preferred", true);
user_pref("media.webrtc.simulcast.vp9.enabled", true);
user_pref("media.webspeech.synth.enabled", false);

user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);

user_pref("network.early-hints.enabled", false);
user_pref("network.early-hints.over-http-v1-1.enabled", false);
user_pref("network.early-hints.preconnect.enabled", false);

user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.preconnect", false);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);

user_pref("permissions.default.image", 0);
user_pref("permissions.default.screen-wake-lock", 0);
user_pref("permissions.manager.defaultsUrl", "");
user_pref("permissions.manager.remote.enabled", false);
user_pref("permissions.media.query.enabled", false);

user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.antitracking.isolateContentScriptResources", true);

user_pref("privacy.restrict3rdpartystorage.heuristic.recently_visited", true);
user_pref("privacy.restrict3rdpartystorage.heuristic.redirect", true);
user_pref("privacy.restrict3rdpartystorage.heuristic.window_open", true);

//////////////////
//// security ////
//////////////////

// enable samesite lax
user_pref("network.cookie.sameSite.laxByDefault", true);
user_pref("network.cookie.sameSite.schemeful", true);

// disable csp reporting
user_pref("security.csp.reporting.enabled", false);

// enable query stripping
user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", true);

// disable vulnerable cipher suites
user_pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
user_pref("security.ssl3.ecdhe_ecdsa_aes_256_sha", false);
user_pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.ecdhe_rsa_aes_256_sha", false);
user_pref("security.ssl3.rsa_aes_128_gcm_sha256", false);
user_pref("security.ssl3.rsa_aes_128_sha", false);
user_pref("security.ssl3.rsa_aes_256_gcm_sha384", false);
user_pref("security.ssl3.rsa_aes_256_sha", false);

// change accept headers to chromes accept headers
user_pref("network.http.accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7");
user_pref("image.http.accept", "image/avif,image/webp,image/apng,image/*,*/*;q=0.8");

// disable webgl (enable if you need)
user_pref("webgl.disabled", true);

// disable debug renderer info if you want to enable webgl
user_pref("webgl.enable-debug-renderer-info", false);

/////////////////////
//// performance ////
/////////////////////

// lower memory usage by reducing amount of entries in back/forward history
user_pref("browser.sessionhistory.max_entries", 32);
user_pref("browser.sessionhistory.max_total_viewers", 4);

// enable h265
user_pref("dom.media.webcodecs.h265.enabled", true);

// increase canvas cache size
user_pref("gfx.canvas.accelerated.cache-items", 8192);
user_pref("gfx.canvas.accelerated.cache-size", 512);

// increase skia cache size
user_pref("gfx.content.skia-font-cache-size", 20);

// enable skia dithering
user_pref("gfx.skia.dithering", true);

// enable webrender
user_pref("gfx.webrender.all", true);
user_pref("gfx.webrender.compositor", true);
user_pref("gfx.webrender.dithering", true);
user_pref("gfx.webrender.layer-compositor", true);

// enable precaching
user_pref("gfx.webrender.precache-shaders", true);
user_pref("gfx.webrender.program-binary-disk", true);

// enable svg filter effects
user_pref("gfx.webrender.svg-filter-effects.feconvolvematrix", true);
user_pref("gfx.webrender.svg-filter-effects.fediffuselighting", true);
user_pref("gfx.webrender.svg-filter-effects.fedisplacementmap", true);
user_pref("gfx.webrender.svg-filter-effects.feimage", true);
user_pref("gfx.webrender.svg-filter-effects.femorphology", true);
user_pref("gfx.webrender.svg-filter-effects.fespecularlighting", true);
user_pref("gfx.webrender.svg-filter-effects.fetile", true);
user_pref("gfx.webrender.svg-filter-effects.feturbulence", true);

// force hardware acceleration
user_pref("media.hardware-video-decoding.force-enabled", true);
user_pref("media.hardware-video-encoding.force-enabled", true);

// increase network buffers
user_pref("network.buffer.cache.count", 48);
user_pref("network.buffer.cache.size", 65535);

// increase max connections for http
user_pref("network.http.max-connections", 1800);
user_pref("network.http.max-persistent-connections-per-server", 10);
user_pref("network.http.max-urgent-start-excessive-connections-per-host", 5);

// increase ssl token capacity
user_pref("network.ssl_tokens_cache_capacity", 10240);

// enable certificate compression
user_pref("security.tls.enable_certificate_compression_abridged", true);

///////////////////////////////////////////////////////////////////////
//// unneeded for me (remove any of these if you need to use them) ////
///////////////////////////////////////////////////////////////////////

// disable accessibility (could increase performance?)
user_pref("accessibility.ARIAElementReflection.enabled", false);
user_pref("accessibility.accesskeycausesactivation", false);
user_pref("accessibility.browsewithcaret_shortcut.enabled", false);
user_pref("accessibility.force_disabled", 1);
user_pref("accessibility.typeaheadfind.enablesound", false);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("accessibility.typeaheadfind.manual", false);
user_pref("accessibility.typeaheadfind.prefillwithselection", false);
user_pref("browser.urlbar.accessibility.tabToSearch.announceResults", false);
user_pref("devtools.accessibility.enabled", false);

// disable safe browsing (could be a security issue)
user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.provider.google.advisoryName", "");
user_pref("browser.safebrowsing.provider.google.advisoryURL", "");
user_pref("browser.safebrowsing.provider.google.lists", "");
user_pref("browser.safebrowsing.provider.google.pver", "");
user_pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", "");
user_pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", "");
user_pref("browser.safebrowsing.provider.google.reportURL", "");
user_pref("browser.safebrowsing.provider.google4.advisoryName", "");
user_pref("browser.safebrowsing.provider.google4.advisoryURL", "");
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
user_pref("browser.safebrowsing.provider.google4.lists", "");
user_pref("browser.safebrowsing.provider.google4.pver", "");
user_pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", "");
user_pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", "");
user_pref("browser.safebrowsing.provider.google4.reportURL", "");
user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
user_pref("browser.safebrowsing.provider.mozilla.lists", "");
user_pref("browser.safebrowsing.provider.mozilla.lists.base", "");
user_pref("browser.safebrowsing.provider.mozilla.lists.content", "");
user_pref("browser.safebrowsing.provider.mozilla.pver", "");
user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");
user_pref("browser.safebrowsing.reportPhishURL", "");

// disable translations
user_pref("browser.translations.automaticallyPopup", false);
user_pref("browser.translations.enable", false);
user_pref("browser.translations.select.enable", false);

// disable middleclick pasting
user_pref("middlemouse.paste", false);

// disable middleclick closing and creating tabs
user_pref("widget.gtk.middle-click-enabled", false);

// disable key for menu bar
user_pref("ui.key.menuAccessKeyFocuses", false);

// disable reader
user_pref("reader.parse-on-load.enabled", false);

// disable picture in picture
user_pref("media.videocontrols.picture-in-picture.enabled", false);
user_pref("media.videocontrols.picture-in-picture.video-toggle.enabled", false);

// hide sidebar
user_pref("sidebar.visibility", "hide-sidebar");

/////////////////////
//// preferences ////
/////////////////////

// fades out unloaded tabs
user_pref("browser.tabs.fadeOutUnloadedTabs", true);

// disable home page
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.page", 3);

// enable autoscroll
user_pref("general.autoScroll", true);

// only show bookmarks on a new tab
user_pref("browser.toolbars.bookmarks.visibility", "newtab");

// disable firefox labs
user_pref("browser.preferences.experimental.hidden", true);
user_pref("browser.preferences.experimental", false);

// disable more from mozilla
user_pref("browser.preferences.moreFromMozilla", true);

// disable scrollbars
user_pref("layout.testing.scrollbars.always-hidden", true);

//////////////////
// annoyances ////
//////////////////

// ai
user_pref("browser.ml.chat.menu", false);
user_pref("browser.ml.chat.page.footerBadge", false);
user_pref("browser.ml.chat.page.menuBadge", false);
user_pref("browser.ml.chat.shortcuts", false);
user_pref("browser.ml.chat.shortcuts.custom", false);
user_pref("browser.ml.chat.sidebar", false);
user_pref("browser.ml.checkForMemory", false);
user_pref("browser.ml.linkPreview.blockListEnabled", false);
user_pref("browser.ml.linkPreview.ignoreMs", 0);
user_pref("browser.ml.linkPreview.longPress", false);
user_pref("browser.ml.linkPreview.longPressMs", 0);
user_pref("browser.ml.linkPreview.outputSentences", 0);
user_pref("browser.ml.linkPreview.recentTypingMs", 0);
user_pref("browser.ml.minimumPhysicalMemory", 0);
user_pref("browser.ml.modelCacheMaxSize", 0);
user_pref("browser.ml.modelCacheTimeout", 0);
user_pref("browser.ml.modelHubRootUrl", "");
user_pref("browser.ml.modelHubUrlTemplate", "");
user_pref("browser.tabs.groups.smart.searchTopicEnabled", false);

// force tabs in titlebar
user_pref("browser.tabs.inTitlebar", 1);

// make firefox show the close tab button with more tabs opened
user_pref("browser.tabs.tabClipWidth", 64);
user_pref("browser.tabs.tabMinWidth", 32);

// disable fullscreen warning
user_pref("full-screen-api.transition.timeout", 0);
user_pref("full-screen-api.warning.delay", 0);
user_pref("full-screen-api.warning.timeout", 0);

//////////////////////////////////////////////////////////////
// features that are on chrome thats not enabled by default //
//////////////////////////////////////////////////////////////

// enable view transitions
user_pref("dom.viewTransitions.enabled", true);

user_pref("services.sync.engine.addons", false);
user_pref("services.sync.engine.bookmarks", false);
user_pref("services.sync.engine.bookmarks.validation.interval", 0);
user_pref("services.sync.engine.bookmarks.validation.maxRecords", 0);
user_pref("services.sync.engine.bookmarks.validation.percentageChance", 0);
user_pref("services.sync.engine.creditcards.available", false);
user_pref("services.sync.engine.history", false);
user_pref("services.sync.engine.passwords", false);
user_pref("services.sync.engine.passwords.validation.interval", 0);
user_pref("services.sync.engine.passwords.validation.maxRecords", 0);
user_pref("services.sync.engine.passwords.validation.percentageChance", 0);
user_pref("services.sync.engine.prefs", false);
user_pref("services.sync.engine.tabs", false);
user_pref("services.sync.engine.tabs.filteredSchemes", "");
user_pref("services.sync.extension-storage.skipPercentageChance", 0);
user_pref("services.sync.lastversion", "");
user_pref("services.sync.log.appender.console", "");
user_pref("services.sync.log.appender.dump", "");
user_pref("services.sync.log.appender.file.level", "");
user_pref("services.sync.log.appender.file.logOnError", false);
user_pref("services.sync.log.appender.file.maxErrorAge", 0);
user_pref("services.sync.log.logger", "");
user_pref("services.sync.log.logger.engine", "");
user_pref("services.sync.maxResyncs", 0);
user_pref("services.sync.scheduler.activeInterval", 0);
user_pref("services.sync.scheduler.fxa.singleDeviceInterval", 0);
user_pref("services.sync.scheduler.idleInterval", 0);
user_pref("services.sync.scheduler.idleTime", 0);
user_pref("services.sync.scheduler.immediateInterval", 0);
user_pref("services.sync.sendVersionInfo", false);
user_pref("services.sync.syncedTabs.showRemoteIcons", false);
user_pref("services.sync.syncedTabs.syncDelayAfterTabChange", 0);
user_pref("services.sync.telemetry.maxPayloadCount", 0);
user_pref("services.sync.telemetry.submissionInterval", 0);
user_pref("signon.firefoxRelay.base_url", "");
user_pref("signon.firefoxRelay.feature", "disabled");
user_pref("signon.firefoxRelay.learn_more_url", "");
user_pref("signon.firefoxRelay.manage_url", "");
user_pref("signon.firefoxRelay.privacy_policy_url", "");
user_pref("signon.firefoxRelay.terms_of_service_url", "");
user_pref("signon.generation.enabled", false);
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("toolkit.shopping.ohttpConfigURL", "");
user_pref("toolkit.shopping.ohttpRelayURL", "");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.winRegisterApplicationRestart", false);
